%% ========================================================================
% One paired Monte Carlo replication
% ========================================================================
%
% Full call chain:
%   s01_mcdt_finite_sample_calibration.m
%       -> runPairedFullGrid.m
%           -> runPairedSimConfig.m
%               -> onePairedReplication.m
%
% Core replication step of the simulation.
% This function generates one Student-t sample, fits the MCD estimator
% from the FSDA toolbox with the asymptotic consistency correction
% controlled by `conflev`, and returns:
%   - the baseline robust distances,
%   - the determinant-corrected robust distances,
%   - the corresponding outlier counts.
%
% If `verifyCorrection` is true, it also checks that the corrected
% distances match the covariance-level correction numerically.
%% ========================================================================

function [mdBase,...
    cntBase,...
    mdMeanRoot,...
    cntMeanRoot,...
    mdRootMeanCov,...
    cntRootMeanCov] = ...
    onePairedReplication(...
    n,...
    p,...
    nu,...
    alpha0,...
    cutoff,...
    factorMeanRoot,...
    factorRootMeanCov,...
    verifyCorrection,...
    conflev)

% Generate uncontaminated Student-t sample
X = randn(n,p).*sqrt(nu./chi2rnd(nu,n,1));

% MCD estimator with asymptotic consistency correction controlled by conflev
RAW = mcd(X,...
    'modelT',nu,...
    'bdp',alpha0,...
    'conflev',conflev,...
    'smallsamplecor',false,...
    'nsamp',500,...
    'refsteps',10,...
    'plots',0,...
    'msg',0,...
    'nocheck',1);

% baseline robust distances
mdBase = RAW.md;

% determinant-adjusted distances
mdMeanRoot    = RAW.md .* factorMeanRoot;
mdRootMeanCov = RAW.md .* factorRootMeanCov;

% outlier counts
cntBase = sum(mdBase > cutoff,1);
cntMeanRoot = sum(mdMeanRoot > cutoff,1);
cntRootMeanCov = sum(mdRootMeanCov > cutoff,1);

if verifyCorrection
    verifyCorrectedMD(...
        X,...
        RAW,...
        mdMeanRoot,...
        cutoff,...
        factorMeanRoot,...
        'mean_root_det');
    verifyCorrectedMD(...
        X,...
        RAW,...
        mdRootMeanCov,...
        cutoff,...
        factorRootMeanCov,...
        'root_det_mean_cov');
end
end

%% ========================================================================
% Verify covariance-level and distance-level correction
% ========================================================================
%
% Full call chain:
%   s01_mcdt_finite_sample_calibration.m
%       -> runPairedFullGrid.m
%           -> runPairedSimConfig.m
%               -> onePairedReplication.m
%                   -> verifyCorrectedMD.m
%
% Checks that applying the determinant correction to the covariance gives
% the same outlier flags as applying it directly to the robust distances.
% If the two disagree, the function warns about flag mismatches and
% numerical differences.
%% ========================================================================

function verifyCorrectedMD(...
    X,...
    RAW,...
    mdCorrected,...
    cutoff,...
    corrFactor,...
    estimatorLabel)

% If Sigma is divided by c, distances are multiplied by c
SigmaCorrected = RAW.cov ./ corrFactor;
Xc = X - RAW.loc;
mdCheck = sum((Xc / SigmaCorrected).*Xc,2);

flagDiff = ...
    (mdCorrected > cutoff) ~= ...
    (mdCheck > cutoff);
flagMismatch=sum(flagDiff(:));

if flagMismatch>0
    warning(...
        'verifyCorrectedMD:flagMismatch',...
        '%s correction: %d flags differ.',...
        estimatorLabel,...
        flagMismatch);
end

relDiff = ...
    max(abs(mdCorrected-mdCheck)) / ...
    max(1,max(abs(mdCorrected)));

if relDiff>1e-6
    warning(...
        'verifyCorrectedMD:numericalMismatch',...
        '%s correction numerical mismatch %.3g',...
        estimatorLabel,...
        relDiff);
end
end

