%% ========================================================================
% Convert result columns to a table
% ========================================================================
%
% Full call chain:
%   s01_mcdt_finite_sample_calibration.m
%       -> runPairedFullGrid.m
%           -> resultColumnsToTable.m
%
% Packs the preallocated result columns into a MATLAB table with the
% variable names used for saving, analysis, and diagnostic plots.
%% ========================================================================

function Results = resultColumnsToTable(cols)
Results = table(...
    cols.n,...
    cols.p,...
    cols.nu,...
    cols.alpha0,...
    cols.conflev,...
    cols.q_asym_sq,...
    cols.q_emp_avgquantile_sq,...
    cols.q_emp_pooled_sq,...
    cols.kappa_RD,...
    cols.q_RD_calibrated_sq,...
    cols.q_asym,...
    cols.q_emp_avgquantile,...
    cols.q_emp_pooled,...
    cols.q_RD_calibrated,...
    cols.emp_size,...
    cols.nominal_size,...
    cols.sizeRatio,...
    cols.emp_size_calibrated,...
    cols.sizeRatio_calibrated,...
    cols.emp_size_pooled,...
    cols.sizeRatio_calibrated_pooled,...
    cols.emp_size_replicationwise,...
    cols.sizeRatio_calibrated_replicationwise,...
    cols.biasdet_found,...
    'VariableNames',...
    {'n',...
    'p',...
    'nu',...
    'alpha0',...
    'conflev',...
    'q_asym_sq',...
    'q_emp_avgquantile_sq',...
    'q_emp_pooled_sq',...
    'kappa_RD',...
    'q_RD_calibrated_sq',...
    'q_asym',...
    'q_emp_avgquantile',...
    'q_emp_pooled',...
    'q_RD_calibrated',...
    'emp_size',...
    'nominal_size',...
    'sizeRatio',...
    'emp_size_calibrated',...
    'sizeRatio_calibrated',...
    'emp_size_pooled',...
    'sizeRatio_calibrated_pooled',...
    'emp_size_replicationwise',...
    'sizeRatio_calibrated_replicationwise',...
    'biasdet_found'});
end
