%% ========================================================================
% Run the paired simulation over the full parameter grid
% ========================================================================
%
% Full call chain:
%   s01_mcdt_finite_sample_calibration.m
%       -> runPairedFullGrid.m
%
% For each combination of (n, p, nu, alpha0), this function:
%   - computes the asymptotic MCD cutoff,
%   - retrieves the determinant-bias correction factors,
%   - runs the split-sample paired Monte Carlo simulation,
%   - stores the baseline and corrected results in separate tables.
%
% Output tables:
%   - ResultsBaseline: asymptotic cutoff, no determinant correction
%   - ResultsDetMeanRoot: correction based on mean_root_det
%   - ResultsDetRootMeanCov: correction based on root_det_mean_cov
%

function [ResultsBaseline, ResultsDetMeanRoot, ResultsDetRootMeanCov] = ...
    runPairedFullGrid(...
        n_vec,...
        p_vec,...
        nu_vec,...
        alpha0_vec,...
        conflev,...
        B,...
        meanRootDetFactorFun,...
        rootDetMeanCovFactorFun,...
        useParfor,...
        VERIFY_BIASDET_CORRECTION, ...
        q_method)

nn = numel(n_vec);
pp = numel(p_vec);
nu_n = numel(nu_vec);
aa = numel(alpha0_vec);
nc = 1; % single conflev
nRows = nn*pp*nu_n*aa*nc;
base = initialiseResultColumns(nRows);
detMeanRoot = initialiseResultColumns(nRows);
detRootMeanCov = initialiseResultColumns(nRows);

row = 0;
ticSim = tic;

for ip = 1:pp
    p = p_vec(ip);
    for iu = 1:nu_n
        nu = nu_vec(iu);
        cutoff = msdcutoff(conflev,p,nu);
        for ia = 1:aa
            alpha0 = alpha0_vec(ia);
            for in = 1:nn
                n = n_vec(in);

                [factorMeanRoot,foundMeanRoot] = ...
                    meanRootDetFactorFun(alpha0,n,p,nu);

                [factorRootMeanCov,foundRootMeanCov] = ...
                    rootDetMeanCovFactorFun(alpha0,n,p,nu);

                [calibBase,...
                    calibMeanRoot,...
                    calibRootMeanCov,...
                    evalBase,...
                    evalMeanRoot,...
                    evalRootMeanCov] = ...
                    runPairedSimConfig(...
                    n,...
                    p,...
                    nu,...
                    alpha0,...
                    B,...
                    cutoff,...
                    factorMeanRoot,...
                    factorRootMeanCov,...
                    useParfor,...
                    VERIFY_BIASDET_CORRECTION,...
                    conflev,...
                    q_method);


                row=row+1;
                base = writeResultRow(...
                    base,...
                    row,...
                    n,...
                    p,...
                    nu,...
                    alpha0,...
                    conflev,...
                    cutoff,...
                    calibBase,...
                    evalBase,...
                    true);
                detMeanRoot = writeResultRow(...
                    detMeanRoot,...
                    row,...
                    n,...
                    p,...
                    nu,...
                    alpha0,...
                    conflev,...
                    cutoff,...
                    calibMeanRoot,...
                    evalMeanRoot,...
                    foundMeanRoot);
                detRootMeanCov = writeResultRow(...
                    detRootMeanCov,...
                    row,...
                    n,...
                    p,...
                    nu,...
                    alpha0,...
                    conflev,...
                    cutoff,...
                    calibRootMeanCov,...
                    evalRootMeanCov,...
                    foundRootMeanCov);
            end
        end
    end
end

fprintf('\nSimulation grid completed in %.1f seconds.\n',...
    toc(ticSim));

ResultsBaseline       = resultColumnsToTable(base);
ResultsDetMeanRoot    = resultColumnsToTable(detMeanRoot);
ResultsDetRootMeanCov = resultColumnsToTable(detRootMeanCov);
end
