%% ========================================================================
% s02_mcdt_interpolation_analysis.m
% ========================================================================
%
% INTERPOLATION ANALYSIS OF THE CALIBRATION OUTPUT
%
% Purpose:
%   Post-process the calibration results produced by
%   s01_mcdt_finite_sample_calibration.m and compare interpolation
%   strategies for the two quantities studied in the paper:
%
%     (A) Section 5.4:
%         delta_hat(n,p,alpha0,nu) = 1 / BiasDet
%
%     (B) Section 6:
%         kappa_RD^delta(n,p,nu,alpha0,conflev)
%
% Workflow:
%   1. Load the calibration CSV files.
%   2. Extract the target quantity for Section 5.4 and Section 6.
%   3. Compare interpolation methods:
%        - scattered linear interpolation
%        - two-dimensional LOESS
%        - PCHIP in n followed by linear interpolation in alpha0
%   4. Export summary tables, dense lookup tables, and diagnostic figures.
%
% Notes:
%   - Section 5.4 uses the mean-root-determinant BiasDet construction.
%   - Section 6 uses the RD calibration output from the main simulation.
%   - No extrapolation is performed; values outside the convex hull are NaN.
%   - The two analyses are saved in separate folders so their outputs
%     cannot be mixed.
%
% Main inputs:
%   - calibration_results: selects the output folder from s01
%   - deltaFile: BiasDet_table_mean_root.csv
%   - rdFile: mcd_heavytails_RD_calibration.csv
%
% Main outputs:
%   - interpolation summaries, lookup tables, and plots for delta_hat
%   - interpolation summaries, lookup tables, and plots for kappa_RD^delta
%
% Dependencies:
%   - MATLAB
%   - Statistics Toolbox
%   - files generated by s01_mcdt_finite_sample_calibration.m
%
% Full call chain:
%   s02_mcdt_interpolation_analysis.m
%       -> analyseTable
%           -> predictLinear
%           -> fitLoessSurface
%               -> evaluateLoess
%           -> evaluateDenseLoess
%               -> evaluateLoess
%           -> makeLoessLookupTable
%           -> predictPchip
%           -> curveRows
%           -> transitionRows
%       -> plotLoessInterpolants
%
% ========================================================================

clear; clc; close all   % cleaning

seed = 20260711;     % Reproducibility
projectRoot = pwd;   % Your project folder: results will be saved there

%% ========================================================================
% SIMULATION SETTINGS
% =========================================================================

% Select which calibration result folder to read from.
%   'paper_all'    -> main paper output
%   'paper_grass'  -> Grass-data variant
%    otherwise     -> user selects the folder name directly
calibration_results = 'paper_all'; 

% Section 5.4 construction to analyse.
% The mean-root version matches the main delta-hat table used in the paper.
deltaConstruction = 'mean_root';

% RD output method to analyse from the calibration database.
rdMethod = 'det_mean_root';

% LOESS smoothing span used for the interpolation fits.
loessSpan      = 0.15;

% Use every `validationStep`-th n value as a held-out point when computing
% validation errors for the interpolation comparison.
validationStep = 5;

% Dense grid used only to export the LOESS surface as a lookup table.
% Values outside the convex hull are left as NaN.
denseNGrid      = 50:1:500;
denseAlpha0Grid = 0.05:0.01:0.50;

% plot controls
producePlots   = true;
produceSurfacePlots = true;

% If empty [], plot every alpha0 surface found in the data.
% Otherwise, plot only the selected alpha0 values.
plotAlpha0Values = [0.05 0.25 0.50];


%% ========================================================================
% STORAGE AND OUTPUT FILES
% ========================================================================
%
% Add the project folders to the MATLAB path so the analysis can call the
% simulation, core, and plotting helpers.
addpath(genpath(fullfile(projectRoot, 'src_srep')));
addpath(genpath(fullfile(projectRoot, 'src_core')));
addpath(genpath(fullfile(projectRoot, 'src_plots')));

% Root folder where all replicability outputs are stored.
resultsRoot    = fullfile(projectRoot, 'REPLICABILITY_RESULTS');

% Timestamp used to create a unique output folder for a specific new run.
ts             = datestr(now, 'yyyy-mm-dd_HHMMSS');

% Select the input folder containing the results from s01.
% The output folder is always kept separate from the input data.
switch calibration_results
    case 'paper_all'
        % This is used for the current draft of the paper
        inputFolder = [resultsRoot filesep 'article' filesep 'Results_correction_alpha0extended_2026-09-27_120522/'];
        % The output root is separate from the simulation results
        outputRoot  = [resultsRoot filesep 'article' filesep 'MCDt_all_interpolation_analysis' '_' ts];
    case 'paper_grass'
        % This is used to cover the case of the Grass dataset
        inputFolder = [resultsRoot filesep 'article' filesep 'Results_correction_p3_nu8_alpha0extended_2026-10-02'];
        % The output root is separate from the simulation results
        outputRoot  = [resultsRoot filesep 'article' filesep 'MCDt_all_interpolation_analysis_p3_nu8' '_' ts];
    otherwise
        inputFolder = [resultsRoot filesep calibration_results];
        outputRoot  = fullfile(resultsRoot, ['interpolation_' ts]);
        mkdir(outputRoot);
end

% Section 5.4 input: BiasDet table produced by estimateBiasDetFactors.m.
% The delta quantity is defined as the reciprocal of BiasDet.
deltaFile = fullfile(inputFolder, 'BiasDet_table_mean_root.csv');

% Section 6 input: RD calibration database produced by s01.
rdFile = fullfile(inputFolder, 'mcd_heavytails_RD_calibration.csv');



%% ------------------------- SECTION 5.4: DELTA -------------------------
%
% Section 5.4 studies the determinant-based finite-sample factor
% delta_hat = 1 / BiasDet.
%
% This block:
%   1. loads the BiasDet calibration table produced by s01,
%   2. computes delta_hat,
%   3. adds the paper's finite-sample diagnostic quantities,
%   4. compares interpolation methods on the delta surface,
%   5. saves the raw rows, summary tables, and dense LOESS lookup table.
%

if ~isfile(deltaFile)
    error('Section 5.4 input file not found: %s', deltaFile);
end
D = readtable(deltaFile);
required = {'alpha0','n','p','nu','BiasDet'};
assert(all(ismember(required,D.Properties.VariableNames)), ...
    'The delta input must contain columns: alpha0, n, p, nu, BiasDet.');

% Finite-sample calibration factor used in Section 5.4.
D.delta_hat = 1 ./ D.BiasDet;
D.quantity = repmat({'delta_hat'},height(D),1);

% Optional finite-sample diagnostics used in the paper.
D.q_n = floor((D.n + D.p + 1) ./ 2);
D.h_n = floor(D.n - 2 .* (D.n - D.q_n) .* D.alpha0);
D.alpha_n = 1 - D.h_n ./ D.n;

% Analyse the delta surface for each (p, nu) slice.
deltaOut = fullfile(outputRoot,'delta_interpolation');
if producePlots, mkdir(fullfile(deltaOut,'plots')); end
[D,DeltaSummary] = analyseTable(D, 'delta_hat', {'p','nu'}, deltaOut, ...
    'delta', loessSpan, validationStep, plotAlpha0Values, ...
    producePlots, produceSurfacePlots, denseNGrid, denseAlpha0Grid);

% Save the dense LOESS lookup table and summary outputs.
writetable(DeltaSummary.loessLookup, fullfile(deltaOut,'delta_loess_lookup.csv'));
writetable(D, fullfile(deltaOut,'delta_analysis_rows.csv'));
writetable(DeltaSummary.surface, fullfile(deltaOut,'delta_surface_summary.csv'));
writetable(DeltaSummary.curve, fullfile(deltaOut,'delta_curve_summary.csv'));
writetable(DeltaSummary.transitions, fullfile(deltaOut,'delta_h_transitions.csv'));
save(fullfile(deltaOut,'MCDt_delta_interpolation_analysis.mat'), ...
    'D','DeltaSummary','deltaFile','deltaConstruction','loessSpan', ...
    'validationStep','plotAlpha0Values','denseNGrid','denseAlpha0Grid');

%% -------------------------- SECTION 6: RD -----------------------------
%
% Section 6 studies the calibrated robust-distance factor
% kappa_RD^delta = q_emp / q_asym.
%
% This block:
%   1. loads the RD calibration database produced by s01,
%   2. filters the rows for the chosen correction method,
%   3. adds the paper's finite-sample diagnostic quantities,
%   4. compares interpolation methods on the kappa_RD surface,
%   5. saves the raw rows, summary tables, and dense LOESS lookup table.
%

if ~isfile(rdFile)
    error('Section 6 input file not found: %s', rdFile);
end
R = readtable(rdFile);
required = {'method','n','p','nu','alpha0','conflev','kappa_RD'};
assert(all(ismember(required,R.Properties.VariableNames)), ...
    'The RD input must contain columns: method, n, p, nu, alpha0, conflev, kappa_RD.');

% Keep only the correction method selected at the top of the script.
R = R(strcmp(string(R.method),rdMethod),:);
if isempty(R)
    error('No RD rows found for method "%s".',rdMethod);
end

% Quantity label used in the exported tables and plots.
R.quantity = repmat({'kappa_RD_delta'},height(R),1);

% Same finite-sample diagnostics used in Section 5.4.
R.q_n = floor((R.n + R.p + 1) ./ 2);
R.h_n = floor(R.n - 2 .* (R.n - R.q_n) .* R.alpha0);
R.alpha_n = 1 - R.h_n ./ R.n;

% Analyse the RD surface for each (p, nu, conflev) slice.
rdOut = fullfile(outputRoot,'RD_interpolation');
if producePlots, mkdir(fullfile(rdOut,'plots')); end
[R,RDSummary] = analyseTable(R, 'kappa_RD', {'p','nu','conflev'}, rdOut, ...
    'RD', loessSpan, validationStep, plotAlpha0Values, ...
    producePlots, produceSurfacePlots, denseNGrid, denseAlpha0Grid);

% Save the dense LOESS lookup table separately from the Section 5.4 table.
writetable(RDSummary.loessLookup, fullfile(rdOut,'RD_loess_lookup.csv'));

% Keep the original RD columns plus the interpolants and residual summaries.
writetable(R, fullfile(rdOut,'RD_analysis_rows.csv'));
writetable(RDSummary.surface, fullfile(rdOut,'RD_surface_summary.csv'));
writetable(RDSummary.curve, fullfile(rdOut,'RD_curve_summary.csv'));
writetable(RDSummary.transitions, fullfile(rdOut,'RD_h_transitions.csv'));
save(fullfile(rdOut,'MCDt_RD_interpolation_analysis.mat'), ...
    'R','RDSummary','rdFile','rdMethod','loessSpan', ...
    'validationStep','plotAlpha0Values','denseNGrid','denseAlpha0Grid');

fprintf('\nFinished. Separate outputs were written to:\n  %s\n  %s\n',deltaOut,rdOut);


%% plot loess interpolants

% Pick one surface to plot
pSel  = 3;
nuSel = 8;
conflevSel = 0.95; % for RD only

[hf_loess_RD , hf_loess_delta] = plotLoessInterpolants(pSel,nuSel,conflevSel,outputRoot);


%% ============================= FUNCTIONS ==============================
function [T,Summary] = analyseTable(T, valueName, keyNames, outDir, prefix, ...
    loessSpan, validationStep, plotAlpha0Values, producePlots, produceSurfacePlots, denseNGrid, denseAlpha0Grid)

T.linear = nan(height(T),1);
T.loess = nan(height(T),1);
T.pchip_n_linear_alpha0 = nan(height(T),1);
SurfaceSummary = table(); CurveSummary = table(); HTransitions = table();
keys = unique(T{:,keyNames},'rows');
loessModels = struct([]);
loessLookup = table();

for ik = 1:size(keys,1)
    inSurface = true(height(T),1);
    keyValues = cell(1,numel(keyNames));
    for j = 1:numel(keyNames)
        inSurface = inSurface & T.(keyNames{j}) == keys(ik,j);
        keyValues{j} = keys(ik,j);
    end
    rows = find(inSurface);
    n = T.n(rows); a = T.alpha0(rows); y = T.(valueName)(rows);
    T.linear(rows) = predictLinear(n,a,y,n,a);

    % Fit one LOESS object for this fixed-indexing-parameter surface.
    % The object and its convex-hull domain are retained for later use.
    [loessFit, loessDomain] = fitLoessSurface(n,a,y,loessSpan);
    T.loess(rows) = evaluateLoess(loessFit,loessDomain,n,a);

    model = struct();
    for jj = 1:numel(keyNames)
        model.(keyNames{jj}) = keys(ik,jj);
    end
    model.fit = loessFit;
    model.domain = loessDomain;
    model.span = loessSpan;
    model.nTraining = n;
    model.alpha0Training = a;
    model.valueTraining = y;

    if isempty(loessModels)
        loessModels = model;
    else
        loessModels(end+1,1) = model;
    end

    % Export a dense lookup representation of this LOESS surface.
    [lookupSurface, lookupN, lookupA] = evaluateDenseLoess(loessFit,loessDomain, ...
        denseNGrid,denseAlpha0Grid);
    lookupTable = makeLoessLookupTable(keyNames,keys(ik,:),lookupN,lookupA,lookupSurface);
    loessLookup = [loessLookup; lookupTable]; %#ok<AGROW>

    T.pchip_n_linear_alpha0(rows) = predictPchip(n,a,y,n,a);

    nGrid = unique(n); validationN = chooseValidationN(nGrid,validationStep);
    fitRows = ~ismember(n,validationN); testRows = ~fitRows;
    if sum(fitRows) >= 4 && any(testRows)
        pred = [predictLinear(n(fitRows),a(fitRows),y(fitRows),n(testRows),a(testRows)), ...
                predictLoess(n(fitRows),a(fitRows),y(fitRows),n(testRows),a(testRows),loessSpan), ...
                predictPchip(n(fitRows),a(fitRows),y(fitRows),n(testRows),a(testRows))];
    else
        pred = nan(sum(testRows),3);
    end
    fitted = [T.linear(rows),T.loess(rows),T.pchip_n_linear_alpha0(rows)];
    names = {'linear';'loess';'pchip_n_linear_alpha0'};
    for ic = 1:3
        s = table(keyValues{:},names(ic),numel(rows),numel(unique(n)),numel(unique(a)), ...
            rmse(y,fitted(:,ic)),mae(y,fitted(:,ic)), ...
            validationRMSE(y(testRows),pred(:,ic)),validationMAE(y(testRows),pred(:,ic)), ...
            'VariableNames',[keyNames,{'candidate','nRows','nN','nAlpha0', ...
            'fitRMSE','fitMAE','validationRMSE','validationMAE'}]);
        SurfaceSummary = [SurfaceSummary;s]; %#ok<AGROW>
    end

    alphaGrid = unique(a)';
    for ia = 1:numel(alphaGrid)
        cr = rows(a == alphaGrid(ia)); [~,ord] = sort(T.n(cr)); cr = cr(ord);
        C = curveRows(T,cr,valueName,'raw_monte_carlo');
        C = [C;curveRows(T,cr,'linear','linear');curveRows(T,cr,'loess','loess'); ...
            curveRows(T,cr,'pchip_n_linear_alpha0','pchip_n_linear_alpha0')];
        CurveSummary = [CurveSummary;C]; %#ok<AGROW>
        HTransitions = [HTransitions;transitionRows(T,cr)]; %#ok<AGROW>
    end

    if producePlots
        cur = T(rows,:); alphaPlot = unique(cur.alpha0)';
        if ~isempty(plotAlpha0Values), alphaPlot = plotAlpha0Values; end
        for ia = 1:numel(alphaPlot)
            plotCurve(cur,keyValues,alphaPlot(ia),outDir,prefix);
        end
        if produceSurfacePlots, plotSurface(cur,keyValues,outDir,prefix,valueName); end
    end
end

% Attach predictions and residuals to the table in the caller's workspace is
% not possible by reference, so save them in the summary object as well.
Summary.surface = SurfaceSummary; Summary.curve = CurveSummary;
Summary.transitions = HTransitions; Summary.rows = T;
Summary.loessModels = loessModels;
Summary.loessLookup = loessLookup;
end

function v = chooseValidationN(nGrid,step)
if numel(nGrid) < 5, v = []; return; end
idx = 3:step:(numel(nGrid)-2); v = nGrid(idx);
end

function z = predictLinear(n,a,y,qN,qA)
F = scatteredInterpolant(n,a,y,'linear','none'); z = F(qN,qA);
end

function [fitObject,domain] = fitLoessSurface(n,a,y,span)
% Fit a two-dimensional LOESS surface and retain its valid convex-hull domain.
% The argument order used by MATLAB's fit object is (alpha0,n).
fitObject = [];
domain = struct('nHull',[],'alpha0Hull',[],'available',false);
if numel(unique(n)) < 3 || numel(unique(a)) < 2
    return;
end
try
    ft = fittype('loess');
    opts = fitoptions('Method','LowessFit','Normalize','on', ...
        'Robust','off','Span',span);
    fitObject = fit([a(:),n(:)],y(:),ft,opts);
    hull = convhull(n(:),a(:));
    domain.nHull = n(hull);
    domain.alpha0Hull = a(hull);
    domain.available = true;
catch ME
    warning('LOESS fit failed: %s',ME.message);
end
end

function z = evaluateLoess(fitObject,domain,qN,qA)
z = nan(size(qN));
if isempty(fitObject) || ~domain.available
    return;
end
sz = size(qN);
qN = qN(:); qA = qA(:);
inside = inpolygon(qN,qA,domain.nHull,domain.alpha0Hull);
z(inside) = fitObject(qA(inside),qN(inside));
z = reshape(z,sz);
end

function [V,N,A] = evaluateDenseLoess(fitObject,domain,nGrid,aGrid)
% Return V with rows corresponding to alpha0 and columns corresponding to n.
[N,A] = meshgrid(nGrid,aGrid);
V = evaluateLoess(fitObject,domain,N,A);
end

function L = makeLoessLookupTable(keyNames,keyValues,N,A,V)
% Store the dense surface in long form so it can be used without cfit.
L = table(N(:),A(:),V(:), ...
    'VariableNames',{'n','alpha0','loess'});
for jj = numel(keyNames):-1:1
    L = addvars(L,repmat(keyValues(jj),height(L),1), ...
        'Before',1,'NewVariableNames',keyNames{jj});
end
end

function z = predictLoess(n,a,y,qN,qA,span)
% Convenience wrapper used for withheld-n validation.
[fitObject,domain] = fitLoessSurface(n,a,y,span);
z = evaluateLoess(fitObject,domain,qN,qA);
end

function z = predictPchip(n,a,y,qN,qA)
z=nan(size(qN)); ag=unique(a)';
for iq=1:numel(qN)
    at=nan(size(ag));
    for ia=1:numel(ag)
        ok=a==ag(ia); [nn,ord]=sort(n(ok)); yy=y(ok); yy=yy(ord);
        if numel(nn)>=2, at(ia)=interp1(nn,yy,qN(iq),'pchip',NaN); end
    end
    ok=~isnan(at); if sum(ok)>=2
        z(iq)=interp1(ag(ok),at(ok),qA(iq),'linear',NaN);
    end
end
if numel(n)>=3
    hull=convhull(n,a); z(~inpolygon(qN,qA,n(hull),a(hull)))=NaN;
end
end

function x=rmse(y,z), ok=~isnan(z); if any(ok), x=sqrt(mean((y(ok)-z(ok)).^2)); else, x=NaN; end, end
function x=mae(y,z), ok=~isnan(z); if any(ok), x=mean(abs(y(ok)-z(ok))); else, x=NaN; end, end
function x=validationRMSE(y,z), x=rmse(y,z); end
function x=validationMAE(y,z), x=mae(y,z); end

function C=curveRows(T,rows,field,candidate)
if strcmp(field,'raw_monte_carlo')
    if ismember('delta_hat',T.Properties.VariableNames), y=T.delta_hat(rows);
    else, y=T.kappa_RD(rows); end
else
    y=T.(field)(rows);
end
steps=diff(y); d=abs(y-1);
C=table(T.p(rows(1)),T.nu(rows(1)),T.alpha0(rows(1)),{candidate},numel(rows), ...
    sum(steps>0),sum(steps<0),d(1),d(end),d(end)<=d(1),sum(diff(d)>0), ...
    'VariableNames',{'p','nu','alpha0','candidate','nPoints','nIncreasingSteps', ...
    'nDecreasingSteps','initialAbsDeviationFromOne','endpointAbsDeviationFromOne', ...
    'endpointMovesTowardOne','awayFromOneSteps'});
if ismember('conflev',T.Properties.VariableNames), C.conflev=T.conflev(rows(1)); C=C(:,{'p','nu','conflev','alpha0','candidate','nPoints','nIncreasingSteps','nDecreasingSteps','initialAbsDeviationFromOne','endpointAbsDeviationFromOne','endpointMovesTowardOne','awayFromOneSteps'}); end
end


function H = transitionRows(T,rows)
if numel(rows) < 2
    H = table();
    return;
end

nPairs = numel(rows) - 1;

p = T.p(rows(1)) * ones(nPairs,1);
nu = T.nu(rows(1)) * ones(nPairs,1);
alpha0 = T.alpha0(rows(1)) * ones(nPairs,1);
nLeft = T.n(rows(1:end-1));
nRight = T.n(rows(2:end));
hLeft = T.h_n(rows(1:end-1));
hRight = T.h_n(rows(2:end));
deltaH = diff(T.h_n(rows));
hIncrementChanged = [false; diff(deltaH) ~= 0];
alphaNLeft = T.alpha_n(rows(1:end-1));
alphaNRight = T.alpha_n(rows(2:end));

if ismember('conflev', T.Properties.VariableNames)
    conflev = T.conflev(rows(1)) * ones(nPairs,1);
    H = table(p,nu,conflev,alpha0,nLeft,nRight,hLeft,hRight,deltaH,hIncrementChanged, ...
        alphaNLeft,alphaNRight, ...
        'VariableNames', {'p','nu','conflev','alpha0','nLeft','nRight','hLeft', ...
        'hRight','deltaH','hIncrementChanged','alphaNLeft','alphaNRight'});
else
    H = table(p,nu,alpha0,nLeft,nRight,hLeft,hRight,deltaH,hIncrementChanged, ...
        alphaNLeft,alphaNRight, ...
        'VariableNames', {'p','nu','alpha0','nLeft','nRight','hLeft','hRight', ...
        'deltaH','hIncrementChanged','alphaNLeft','alphaNRight'});
end
end


function plotCurve(T,key,alpha,outDir,prefix)
cur=sortrows(T(T.alpha0==alpha,:),'n');
if isempty(cur), return; end
if ismember('delta_hat',T.Properties.VariableNames), raw=cur.delta_hat; ylab='\\hat{\\delta}';
else, raw=cur.kappa_RD; ylab='\\kappa_{RD}^{\\delta}'; end
figure('Visible','off','Position',[100 100 1100 750]); names={'linear','loess','pchip_n_linear_alpha0'};
for i=1:3, subplot(2,2,i); plot(cur.n,raw,'ko','MarkerFaceColor','k'); hold on; plot(cur.n,cur.(names{i}),'-','LineWidth',1.7); grid on; xlabel('n'); ylabel(ylab); title(names{i},'Interpreter','none'); end
subplot(2,2,4); plot(cur.n,raw-1,'o-'); hold on; yline(0,'--k'); yyaxis right; stairs(cur.n,cur.h_n,'s-'); ylabel('h_n'); yyaxis left; xlabel('n'); ylabel([ylab,' - 1']); grid on
tag=keyTag(key); saveas(gcf,fullfile(outDir,'plots',sprintf('%s_curve_%s_alpha%g.png',prefix,tag,alpha))); close(gcf)
end

function tag=keyTag(key)
tag=sprintf('p%g_nu%g',key{1},key{2});
if numel(key)>=3
    tag=[tag,sprintf('_conf%g',key{3})];
end
end

function plotSurface(T,key,outDir,prefix,valueName)
ng=unique(T.n)'; 
ag=unique(T.alpha0)'; 
names={valueName,'linear','loess','pchip_n_linear_alpha0'}; 
figure('Visible','off','Position',[100 100 1200 800]);
for i=1:4
    V=nan(numel(ag),numel(ng)); 
    for ia=1:numel(ag)
        for in=1:numel(ng)
            r=T.alpha0==ag(ia)&T.n==ng(in); 
            if any(r)
                V(ia,in)=T.(names{i})(find(r,1)); 
            end
        end
    end
    subplot(2,2,i); 
    surf(ng,ag,V,'EdgeColor','none'); 
    view(45,30); 
    colorbar; 
    grid on; 
    xlabel('n'); 
    ylabel('alpha_0'); 
    zlabel(names{i},'Interpreter','none'); 
    title(names{i},'Interpreter','none'); 
end
tag=keyTag(key); 
saveas(gcf,fullfile(outDir,'plots',sprintf('%s_surface_%s.png',prefix,tag))); 
close(gcf)
end




